# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindows.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import classcify

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(807, 546)
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setGeometry(QtCore.QRect(130, 70, 531, 301))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 529, 299))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.contentBox = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.contentBox.setGeometry(QtCore.QRect(0, 0, 531, 301))
        self.contentBox.setObjectName("contentBox")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(220, 10, 401, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 70, 71, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 400, 181, 41))
        self.label_3.setObjectName("label_3")
        self.result = QtWidgets.QLabel(Dialog)
        self.result.setGeometry(QtCore.QRect(270, 410, 161, 21))
        self.result.setObjectName("result")
        self.calButton = QtWidgets.QPushButton(Dialog)
        self.calButton.setGeometry(QtCore.QRect(240, 470, 93, 28))
        self.calButton.setObjectName("calButton")
        self.resetButton = QtWidgets.QPushButton(Dialog)
        self.resetButton.setGeometry(QtCore.QRect(470, 470, 93, 28))
        self.resetButton.setObjectName("resetButton")
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Classify Window"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Phân loại Email Tiếng Việt</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Nội Dung</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Kết quả phân loại</span></p></body></html>"))
        self.result.setText(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))
        self.calButton.setText(_translate("Dialog", "Calculate"))
        self.resetButton.setText(_translate("Dialog", "Reset"))
        self.calButton.clicked.connect(self.clickOK)
        self.resetButton.clicked.connect(self.reset)
    def clickOK(self):
        text=self.contentBox.toPlainText()
        text = text.replace('\n', '')
        text = text.replace('.', '')
        self.contentBox.setText(text)
        status = classcify.process_word(text)
        if status==1:
            self.result.setText("1")
        else:
            self.result.setText("0")
    def reset(self):
        self.contentBox.setText("")
        self.result.setText("")
